version: '2'
services:
  db:
    image: mariadb:5.5
    ports:
        - 3306:3306
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: magento
        MYSQL_USER: magento
        MYSQL_PASSWORD: magento
  dbadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 2080:80
    links:
      - db:mysql
    environment:
     MYSQL_ROOT_PASSWORD: root
  php:
    image: lrkwz/docker-php-magento-ready:7-fpm
    build: .
    environment:
      XDEBUG_CONFIG: remote_connect_back=1 remote_port=9001 remote_host=127.17.0.1
    volumes:
    - ./codebase:/usr/share/nginx/html
   # These will be dropped when the container is removed, leaving the codebase clean
    - /usr/share/nginx/html/var/cache
    - /usr/share/nginx/html/var
    # Log files in host's directory are easier to look for
    - ./logs/magento:/usr/share/nginx/html/var/log
    links:
        - db
        - mail
    working_dir: /usr/share/nginx/html
  nginx:
    image: nginx:stable-alpine
    ports:
        - 80:80
    links:
        - php
    volumes:
    - ./codebase:/usr/share/nginx/html
    # Log files in host's directory are easier to look for
    - ./logs/nginx/:/var/log/nginx/
  mail:
    image: mailhog/mailhog
    ports:
      - 1080:8025
      - 25:1025
    volumes:
    - ./logs/mail:/var/mail
